name: Generate API Index
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.0
      - name: Checkout googleapis (this repository)
        uses: actions/checkout@v2
      - name: Checkout index generator
        uses: actions/checkout@v2
        with:
          repository: dwsupplee/googleapis-api-index-generator
          path: gen
      - name: Generate API index
        run: |
          gen/scripts/generate-schema.sh
          gen/scripts/generate-index.sh $PWD
          cp gen/tmp/api-index-v1.json $PWD
      - name: Commit API index
        run: |
          git config user.name "Google APIs"
          git add api-index-v1.json
          git commit -m "chore: regenerate API index"
          git push
